### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Yegorov** [Yegorov/rails_admin_yamap_field#1]
- [x] add readme and license
- [ ] add extra settings for field
- [x] publish in RubyGems
- [ ] add example app

**Comment by Yegorov** [comment]
- [ ] Fix for one-to-many map init
- [ ] Add getting zoom level option from db
- [ ] Add support render [static map](https://tech.yandex.ru/maps/doc/staticapi/1.x/dg/concepts/input_params-docpage/) for index action
